/**
 * Le but de ce programme est de donner un outil simple permettant d'obtenir 
 * rapidement le code d'une couleur donnée.
 *
 * Le code source suivant ne constitue pas un tutoriel.
 * De surcroit, il n'utilise aucune nouvelle fonctionnalité de la librairie MLV.
 * Vous pouvez donc passer à l'exemple suivant qui sera plus instructif.
 */

#include <MLV/experimental/window.hpp>
#include <utility>
#include <string>
#include <cmath>

typedef std::pair<mlv::color_t, std::string> color_pair;

//
// Attention ! 
// Pour pouvoir compiler ce programme sous windows et sous macintosh,
// il faut, pour la déclaration du main, respecter strictement la syntaxe
// suivante :
//
int main( int argc, char *argv[] ){

	#define NB_COULEUR 752
	 color_pair couleurs[NB_COULEUR] = {
		color_pair(mlv::color::snow, "mlv::color::snow" ),
		color_pair(mlv::color::ghost_white, "mlv::color::ghost_white" ),
		color_pair(mlv::color::ghostwhite, "mlv::color::ghostwhite" ),
		color_pair(mlv::color::white_smoke, "mlv::color::white_smoke" ),
		color_pair(mlv::color::whitesmoke, "mlv::color::whitesmoke" ),
		color_pair(mlv::color::gainsboro, "mlv::color::gainsboro" ),
		color_pair(mlv::color::floral_white, "mlv::color::floral_white" ),
		color_pair(mlv::color::floralwhite, "mlv::color::floralwhite" ),
		color_pair(mlv::color::old_lace, "mlv::color::old_lace" ),
		color_pair(mlv::color::oldlace, "mlv::color::oldlace" ),
		color_pair(mlv::color::linen, "mlv::color::linen" ),
		color_pair(mlv::color::antique_white, "mlv::color::antique_white" ),
		color_pair(mlv::color::antiquewhite, "mlv::color::antiquewhite" ),
		color_pair(mlv::color::papaya_whip, "mlv::color::papaya_whip" ),
		color_pair(mlv::color::papayawhip, "mlv::color::papayawhip" ),
		color_pair(mlv::color::blanched_almond, "mlv::color::blanched_almond" ),
		color_pair(mlv::color::blanchedalmond, "mlv::color::blanchedalmond" ),
		color_pair(mlv::color::bisque, "mlv::color::bisque" ),
		color_pair(mlv::color::peach_puff, "mlv::color::peach_puff" ),
		color_pair(mlv::color::peachpuff, "mlv::color::peachpuff" ),
		color_pair(mlv::color::navajo_white, "mlv::color::navajo_white" ),
		color_pair(mlv::color::navajowhite, "mlv::color::navajowhite" ),
		color_pair(mlv::color::moccasin, "mlv::color::moccasin" ),
		color_pair(mlv::color::cornsilk, "mlv::color::cornsilk" ),
		color_pair(mlv::color::ivory, "mlv::color::ivory" ),
		color_pair(mlv::color::lemon_chiffon, "mlv::color::lemon_chiffon" ),
		color_pair(mlv::color::lemonchiffon, "mlv::color::lemonchiffon" ),
		color_pair(mlv::color::seashell, "mlv::color::seashell" ),
		color_pair(mlv::color::honeydew, "mlv::color::honeydew" ),
		color_pair(mlv::color::mint_cream, "mlv::color::mint_cream" ),
		color_pair(mlv::color::mintcream, "mlv::color::mintcream" ),
		color_pair(mlv::color::azure, "mlv::color::azure" ),
		color_pair(mlv::color::alice_blue, "mlv::color::alice_blue" ),
		color_pair(mlv::color::aliceblue, "mlv::color::aliceblue" ),
		color_pair(mlv::color::lavender, "mlv::color::lavender" ),
		color_pair(mlv::color::lavender_blush, "mlv::color::lavender_blush" ),
		color_pair(mlv::color::lavenderblush, "mlv::color::lavenderblush" ),
		color_pair(mlv::color::misty_rose, "mlv::color::misty_rose" ),
		color_pair(mlv::color::mistyrose, "mlv::color::mistyrose" ),
		color_pair(mlv::color::white, "mlv::color::white" ),
		color_pair(mlv::color::black, "mlv::color::black" ),
		color_pair(mlv::color::dark_slate_gray, "mlv::color::dark_slate_gray" ),
		color_pair(mlv::color::darkslategray, "mlv::color::darkslategray" ),
		color_pair(mlv::color::dark_slate_grey, "mlv::color::dark_slate_grey" ),
		color_pair(mlv::color::darkslategrey, "mlv::color::darkslategrey" ),
		color_pair(mlv::color::dim_gray, "mlv::color::dim_gray" ),
		color_pair(mlv::color::dimgray, "mlv::color::dimgray" ),
		color_pair(mlv::color::dim_grey, "mlv::color::dim_grey" ),
		color_pair(mlv::color::dimgrey, "mlv::color::dimgrey" ),
		color_pair(mlv::color::slate_gray, "mlv::color::slate_gray" ),
		color_pair(mlv::color::slategray, "mlv::color::slategray" ),
		color_pair(mlv::color::slate_grey, "mlv::color::slate_grey" ),
		color_pair(mlv::color::slategrey, "mlv::color::slategrey" ),
		color_pair(mlv::color::light_slate_gray, "mlv::color::light_slate_gray" ),
		color_pair(mlv::color::lightslategray, "mlv::color::lightslategray" ),
		color_pair(mlv::color::light_slate_grey, "mlv::color::light_slate_grey" ),
		color_pair(mlv::color::lightslategrey, "mlv::color::lightslategrey" ),
		color_pair(mlv::color::gray, "mlv::color::gray" ),
		color_pair(mlv::color::grey, "mlv::color::grey" ),
		color_pair(mlv::color::light_grey, "mlv::color::light_grey" ),
		color_pair(mlv::color::lightgrey, "mlv::color::lightgrey" ),
		color_pair(mlv::color::light_gray, "mlv::color::light_gray" ),
		color_pair(mlv::color::lightgray, "mlv::color::lightgray" ),
		color_pair(mlv::color::midnight_blue, "mlv::color::midnight_blue" ),
		color_pair(mlv::color::midnightblue, "mlv::color::midnightblue" ),
		color_pair(mlv::color::navy, "mlv::color::navy" ),
		color_pair(mlv::color::navy_blue, "mlv::color::navy_blue" ),
		color_pair(mlv::color::navyblue, "mlv::color::navyblue" ),
		color_pair(mlv::color::cornflower_blue, "mlv::color::cornflower_blue" ),
		color_pair(mlv::color::cornflowerblue, "mlv::color::cornflowerblue" ),
		color_pair(mlv::color::dark_slate_blue, "mlv::color::dark_slate_blue" ),
		color_pair(mlv::color::darkslateblue, "mlv::color::darkslateblue" ),
		color_pair(mlv::color::slate_blue, "mlv::color::slate_blue" ),
		color_pair(mlv::color::slateblue, "mlv::color::slateblue" ),
		color_pair(mlv::color::medium_slate_blue, "mlv::color::medium_slate_blue" ),
		color_pair(mlv::color::mediumslateblue, "mlv::color::mediumslateblue" ),
		color_pair(mlv::color::light_slate_blue, "mlv::color::light_slate_blue" ),
		color_pair(mlv::color::lightslateblue, "mlv::color::lightslateblue" ),
		color_pair(mlv::color::medium_blue, "mlv::color::medium_blue" ),
		color_pair(mlv::color::mediumblue, "mlv::color::mediumblue" ),
		color_pair(mlv::color::royal_blue, "mlv::color::royal_blue" ),
		color_pair(mlv::color::royalblue, "mlv::color::royalblue" ),
		color_pair(mlv::color::blue, "mlv::color::blue" ),
		color_pair(mlv::color::dodger_blue, "mlv::color::dodger_blue" ),
		color_pair(mlv::color::dodgerblue, "mlv::color::dodgerblue" ),
		color_pair(mlv::color::deep_sky_blue, "mlv::color::deep_sky_blue" ),
		color_pair(mlv::color::deepskyblue, "mlv::color::deepskyblue" ),
		color_pair(mlv::color::sky_blue, "mlv::color::sky_blue" ),
		color_pair(mlv::color::skyblue, "mlv::color::skyblue" ),
		color_pair(mlv::color::light_sky_blue, "mlv::color::light_sky_blue" ),
		color_pair(mlv::color::lightskyblue, "mlv::color::lightskyblue" ),
		color_pair(mlv::color::steel_blue, "mlv::color::steel_blue" ),
		color_pair(mlv::color::steelblue, "mlv::color::steelblue" ),
		color_pair(mlv::color::light_steel_blue, "mlv::color::light_steel_blue" ),
		color_pair(mlv::color::lightsteelblue, "mlv::color::lightsteelblue" ),
		color_pair(mlv::color::light_blue, "mlv::color::light_blue" ),
		color_pair(mlv::color::lightblue, "mlv::color::lightblue" ),
		color_pair(mlv::color::powder_blue, "mlv::color::powder_blue" ),
		color_pair(mlv::color::powderblue, "mlv::color::powderblue" ),
		color_pair(mlv::color::pale_turquoise, "mlv::color::pale_turquoise" ),
		color_pair(mlv::color::paleturquoise, "mlv::color::paleturquoise" ),
		color_pair(mlv::color::dark_turquoise, "mlv::color::dark_turquoise" ),
		color_pair(mlv::color::darkturquoise, "mlv::color::darkturquoise" ),
		color_pair(mlv::color::medium_turquoise, "mlv::color::medium_turquoise" ),
		color_pair(mlv::color::mediumturquoise, "mlv::color::mediumturquoise" ),
		color_pair(mlv::color::turquoise, "mlv::color::turquoise" ),
		color_pair(mlv::color::cyan, "mlv::color::cyan" ),
		color_pair(mlv::color::light_cyan, "mlv::color::light_cyan" ),
		color_pair(mlv::color::lightcyan, "mlv::color::lightcyan" ),
		color_pair(mlv::color::cadet_blue, "mlv::color::cadet_blue" ),
		color_pair(mlv::color::cadetblue, "mlv::color::cadetblue" ),
		color_pair(mlv::color::medium_aquamarine, "mlv::color::medium_aquamarine" ),
		color_pair(mlv::color::mediumaquamarine, "mlv::color::mediumaquamarine" ),
		color_pair(mlv::color::aquamarine, "mlv::color::aquamarine" ),
		color_pair(mlv::color::dark_green, "mlv::color::dark_green" ),
		color_pair(mlv::color::darkgreen, "mlv::color::darkgreen" ),
		color_pair(mlv::color::dark_olive_green, "mlv::color::dark_olive_green" ),
		color_pair(mlv::color::darkolivegreen, "mlv::color::darkolivegreen" ),
		color_pair(mlv::color::dark_sea_green, "mlv::color::dark_sea_green" ),
		color_pair(mlv::color::darkseagreen, "mlv::color::darkseagreen" ),
		color_pair(mlv::color::sea_green, "mlv::color::sea_green" ),
		color_pair(mlv::color::seagreen, "mlv::color::seagreen" ),
		color_pair(mlv::color::medium_sea_green, "mlv::color::medium_sea_green" ),
		color_pair(mlv::color::mediumseagreen, "mlv::color::mediumseagreen" ),
		color_pair(mlv::color::light_sea_green, "mlv::color::light_sea_green" ),
		color_pair(mlv::color::lightseagreen, "mlv::color::lightseagreen" ),
		color_pair(mlv::color::pale_green, "mlv::color::pale_green" ),
		color_pair(mlv::color::palegreen, "mlv::color::palegreen" ),
		color_pair(mlv::color::spring_green, "mlv::color::spring_green" ),
		color_pair(mlv::color::springgreen, "mlv::color::springgreen" ),
		color_pair(mlv::color::lawn_green, "mlv::color::lawn_green" ),
		color_pair(mlv::color::lawngreen, "mlv::color::lawngreen" ),
		color_pair(mlv::color::green, "mlv::color::green" ),
		color_pair(mlv::color::chartreuse, "mlv::color::chartreuse" ),
		color_pair(mlv::color::medium_spring_green, "mlv::color::medium_spring_green" ),
		color_pair(mlv::color::mediumspringgreen, "mlv::color::mediumspringgreen" ),
		color_pair(mlv::color::green_yellow, "mlv::color::green_yellow" ),
		color_pair(mlv::color::greenyellow, "mlv::color::greenyellow" ),
		color_pair(mlv::color::lime_green, "mlv::color::lime_green" ),
		color_pair(mlv::color::limegreen, "mlv::color::limegreen" ),
		color_pair(mlv::color::yellow_green, "mlv::color::yellow_green" ),
		color_pair(mlv::color::yellowgreen, "mlv::color::yellowgreen" ),
		color_pair(mlv::color::forest_green, "mlv::color::forest_green" ),
		color_pair(mlv::color::forestgreen, "mlv::color::forestgreen" ),
		color_pair(mlv::color::olive_drab, "mlv::color::olive_drab" ),
		color_pair(mlv::color::olivedrab, "mlv::color::olivedrab" ),
		color_pair(mlv::color::dark_khaki, "mlv::color::dark_khaki" ),
		color_pair(mlv::color::darkkhaki, "mlv::color::darkkhaki" ),
		color_pair(mlv::color::khaki, "mlv::color::khaki" ),
		color_pair(mlv::color::pale_goldenrod, "mlv::color::pale_goldenrod" ),
		color_pair(mlv::color::palegoldenrod, "mlv::color::palegoldenrod" ),
		color_pair(mlv::color::light_goldenrod_yellow, "mlv::color::light_goldenrod_yellow" ),
		color_pair(mlv::color::lightgoldenrodyellow, "mlv::color::lightgoldenrodyellow" ),
		color_pair(mlv::color::light_yellow, "mlv::color::light_yellow" ),
		color_pair(mlv::color::lightyellow, "mlv::color::lightyellow" ),
		color_pair(mlv::color::yellow, "mlv::color::yellow" ),
		color_pair(mlv::color::gold, "mlv::color::gold" ),
		color_pair(mlv::color::light_goldenrod, "mlv::color::light_goldenrod" ),
		color_pair(mlv::color::lightgoldenrod, "mlv::color::lightgoldenrod" ),
		color_pair(mlv::color::goldenrod, "mlv::color::goldenrod" ),
		color_pair(mlv::color::dark_goldenrod, "mlv::color::dark_goldenrod" ),
		color_pair(mlv::color::darkgoldenrod, "mlv::color::darkgoldenrod" ),
		color_pair(mlv::color::rosy_brown, "mlv::color::rosy_brown" ),
		color_pair(mlv::color::rosybrown, "mlv::color::rosybrown" ),
		color_pair(mlv::color::indian_red, "mlv::color::indian_red" ),
		color_pair(mlv::color::indianred, "mlv::color::indianred" ),
		color_pair(mlv::color::saddle_brown, "mlv::color::saddle_brown" ),
		color_pair(mlv::color::saddlebrown, "mlv::color::saddlebrown" ),
		color_pair(mlv::color::sienna, "mlv::color::sienna" ),
		color_pair(mlv::color::peru, "mlv::color::peru" ),
		color_pair(mlv::color::burlywood, "mlv::color::burlywood" ),
		color_pair(mlv::color::beige, "mlv::color::beige" ),
		color_pair(mlv::color::wheat, "mlv::color::wheat" ),
		color_pair(mlv::color::sandy_brown, "mlv::color::sandy_brown" ),
		color_pair(mlv::color::sandybrown, "mlv::color::sandybrown" ),
		color_pair(mlv::color::tan, "mlv::color::tan" ),
		color_pair(mlv::color::chocolate, "mlv::color::chocolate" ),
		color_pair(mlv::color::firebrick, "mlv::color::firebrick" ),
		color_pair(mlv::color::brown, "mlv::color::brown" ),
		color_pair(mlv::color::dark_salmon, "mlv::color::dark_salmon" ),
		color_pair(mlv::color::darksalmon, "mlv::color::darksalmon" ),
		color_pair(mlv::color::salmon, "mlv::color::salmon" ),
		color_pair(mlv::color::light_salmon, "mlv::color::light_salmon" ),
		color_pair(mlv::color::lightsalmon, "mlv::color::lightsalmon" ),
		color_pair(mlv::color::orange, "mlv::color::orange" ),
		color_pair(mlv::color::dark_orange, "mlv::color::dark_orange" ),
		color_pair(mlv::color::darkorange, "mlv::color::darkorange" ),
		color_pair(mlv::color::coral, "mlv::color::coral" ),
		color_pair(mlv::color::light_coral, "mlv::color::light_coral" ),
		color_pair(mlv::color::lightcoral, "mlv::color::lightcoral" ),
		color_pair(mlv::color::tomato, "mlv::color::tomato" ),
		color_pair(mlv::color::orange_red, "mlv::color::orange_red" ),
		color_pair(mlv::color::orangered, "mlv::color::orangered" ),
		color_pair(mlv::color::red, "mlv::color::red" ),
		color_pair(mlv::color::hot_pink, "mlv::color::hot_pink" ),
		color_pair(mlv::color::hotpink, "mlv::color::hotpink" ),
		color_pair(mlv::color::deep_pink, "mlv::color::deep_pink" ),
		color_pair(mlv::color::deeppink, "mlv::color::deeppink" ),
		color_pair(mlv::color::pink, "mlv::color::pink" ),
		color_pair(mlv::color::light_pink, "mlv::color::light_pink" ),
		color_pair(mlv::color::lightpink, "mlv::color::lightpink" ),
		color_pair(mlv::color::pale_violet_red, "mlv::color::pale_violet_red" ),
		color_pair(mlv::color::palevioletred, "mlv::color::palevioletred" ),
		color_pair(mlv::color::maroon, "mlv::color::maroon" ),
		color_pair(mlv::color::medium_violet_red, "mlv::color::medium_violet_red" ),
		color_pair(mlv::color::mediumvioletred, "mlv::color::mediumvioletred" ),
		color_pair(mlv::color::violet_red, "mlv::color::violet_red" ),
		color_pair(mlv::color::violetred, "mlv::color::violetred" ),
		color_pair(mlv::color::magenta, "mlv::color::magenta" ),
		color_pair(mlv::color::violet, "mlv::color::violet" ),
		color_pair(mlv::color::plum, "mlv::color::plum" ),
		color_pair(mlv::color::orchid, "mlv::color::orchid" ),
		color_pair(mlv::color::medium_orchid, "mlv::color::medium_orchid" ),
		color_pair(mlv::color::mediumorchid, "mlv::color::mediumorchid" ),
		color_pair(mlv::color::dark_orchid, "mlv::color::dark_orchid" ),
		color_pair(mlv::color::darkorchid, "mlv::color::darkorchid" ),
		color_pair(mlv::color::dark_violet, "mlv::color::dark_violet" ),
		color_pair(mlv::color::darkviolet, "mlv::color::darkviolet" ),
		color_pair(mlv::color::blue_violet, "mlv::color::blue_violet" ),
		color_pair(mlv::color::blueviolet, "mlv::color::blueviolet" ),
		color_pair(mlv::color::purple, "mlv::color::purple" ),
		color_pair(mlv::color::medium_purple, "mlv::color::medium_purple" ),
		color_pair(mlv::color::mediumpurple, "mlv::color::mediumpurple" ),
		color_pair(mlv::color::thistle, "mlv::color::thistle" ),
		color_pair(mlv::color::snow1, "mlv::color::snow1" ),
		color_pair(mlv::color::snow2, "mlv::color::snow2" ),
		color_pair(mlv::color::snow3, "mlv::color::snow3" ),
		color_pair(mlv::color::snow4, "mlv::color::snow4" ),
		color_pair(mlv::color::seashell1, "mlv::color::seashell1" ),
		color_pair(mlv::color::seashell2, "mlv::color::seashell2" ),
		color_pair(mlv::color::seashell3, "mlv::color::seashell3" ),
		color_pair(mlv::color::seashell4, "mlv::color::seashell4" ),
		color_pair(mlv::color::antiquewhite1, "mlv::color::antiquewhite1" ),
		color_pair(mlv::color::antiquewhite2, "mlv::color::antiquewhite2" ),
		color_pair(mlv::color::antiquewhite3, "mlv::color::antiquewhite3" ),
		color_pair(mlv::color::antiquewhite4, "mlv::color::antiquewhite4" ),
		color_pair(mlv::color::bisque1, "mlv::color::bisque1" ),
		color_pair(mlv::color::bisque2, "mlv::color::bisque2" ),
		color_pair(mlv::color::bisque3, "mlv::color::bisque3" ),
		color_pair(mlv::color::bisque4, "mlv::color::bisque4" ),
		color_pair(mlv::color::peachpuff1, "mlv::color::peachpuff1" ),
		color_pair(mlv::color::peachpuff2, "mlv::color::peachpuff2" ),
		color_pair(mlv::color::peachpuff3, "mlv::color::peachpuff3" ),
		color_pair(mlv::color::peachpuff4, "mlv::color::peachpuff4" ),
		color_pair(mlv::color::navajowhite1, "mlv::color::navajowhite1" ),
		color_pair(mlv::color::navajowhite2, "mlv::color::navajowhite2" ),
		color_pair(mlv::color::navajowhite3, "mlv::color::navajowhite3" ),
		color_pair(mlv::color::navajowhite4, "mlv::color::navajowhite4" ),
		color_pair(mlv::color::lemonchiffon1, "mlv::color::lemonchiffon1" ),
		color_pair(mlv::color::lemonchiffon2, "mlv::color::lemonchiffon2" ),
		color_pair(mlv::color::lemonchiffon3, "mlv::color::lemonchiffon3" ),
		color_pair(mlv::color::lemonchiffon4, "mlv::color::lemonchiffon4" ),
		color_pair(mlv::color::cornsilk1, "mlv::color::cornsilk1" ),
		color_pair(mlv::color::cornsilk2, "mlv::color::cornsilk2" ),
		color_pair(mlv::color::cornsilk3, "mlv::color::cornsilk3" ),
		color_pair(mlv::color::cornsilk4, "mlv::color::cornsilk4" ),
		color_pair(mlv::color::ivory1, "mlv::color::ivory1" ),
		color_pair(mlv::color::ivory2, "mlv::color::ivory2" ),
		color_pair(mlv::color::ivory3, "mlv::color::ivory3" ),
		color_pair(mlv::color::ivory4, "mlv::color::ivory4" ),
		color_pair(mlv::color::honeydew1, "mlv::color::honeydew1" ),
		color_pair(mlv::color::honeydew2, "mlv::color::honeydew2" ),
		color_pair(mlv::color::honeydew3, "mlv::color::honeydew3" ),
		color_pair(mlv::color::honeydew4, "mlv::color::honeydew4" ),
		color_pair(mlv::color::lavenderblush1, "mlv::color::lavenderblush1" ),
		color_pair(mlv::color::lavenderblush2, "mlv::color::lavenderblush2" ),
		color_pair(mlv::color::lavenderblush3, "mlv::color::lavenderblush3" ),
		color_pair(mlv::color::lavenderblush4, "mlv::color::lavenderblush4" ),
		color_pair(mlv::color::mistyrose1, "mlv::color::mistyrose1" ),
		color_pair(mlv::color::mistyrose2, "mlv::color::mistyrose2" ),
		color_pair(mlv::color::mistyrose3, "mlv::color::mistyrose3" ),
		color_pair(mlv::color::mistyrose4, "mlv::color::mistyrose4" ),
		color_pair(mlv::color::azure1, "mlv::color::azure1" ),
		color_pair(mlv::color::azure2, "mlv::color::azure2" ),
		color_pair(mlv::color::azure3, "mlv::color::azure3" ),
		color_pair(mlv::color::azure4, "mlv::color::azure4" ),
		color_pair(mlv::color::slateblue1, "mlv::color::slateblue1" ),
		color_pair(mlv::color::slateblue2, "mlv::color::slateblue2" ),
		color_pair(mlv::color::slateblue3, "mlv::color::slateblue3" ),
		color_pair(mlv::color::slateblue4, "mlv::color::slateblue4" ),
		color_pair(mlv::color::royalblue1, "mlv::color::royalblue1" ),
		color_pair(mlv::color::royalblue2, "mlv::color::royalblue2" ),
		color_pair(mlv::color::royalblue3, "mlv::color::royalblue3" ),
		color_pair(mlv::color::royalblue4, "mlv::color::royalblue4" ),
		color_pair(mlv::color::blue1, "mlv::color::blue1" ),
		color_pair(mlv::color::blue2, "mlv::color::blue2" ),
		color_pair(mlv::color::blue3, "mlv::color::blue3" ),
		color_pair(mlv::color::blue4, "mlv::color::blue4" ),
		color_pair(mlv::color::dodgerblue1, "mlv::color::dodgerblue1" ),
		color_pair(mlv::color::dodgerblue2, "mlv::color::dodgerblue2" ),
		color_pair(mlv::color::dodgerblue3, "mlv::color::dodgerblue3" ),
		color_pair(mlv::color::dodgerblue4, "mlv::color::dodgerblue4" ),
		color_pair(mlv::color::steelblue1, "mlv::color::steelblue1" ),
		color_pair(mlv::color::steelblue2, "mlv::color::steelblue2" ),
		color_pair(mlv::color::steelblue3, "mlv::color::steelblue3" ),
		color_pair(mlv::color::steelblue4, "mlv::color::steelblue4" ),
		color_pair(mlv::color::deepskyblue1, "mlv::color::deepskyblue1" ),
		color_pair(mlv::color::deepskyblue2, "mlv::color::deepskyblue2" ),
		color_pair(mlv::color::deepskyblue3, "mlv::color::deepskyblue3" ),
		color_pair(mlv::color::deepskyblue4, "mlv::color::deepskyblue4" ),
		color_pair(mlv::color::skyblue1, "mlv::color::skyblue1" ),
		color_pair(mlv::color::skyblue2, "mlv::color::skyblue2" ),
		color_pair(mlv::color::skyblue3, "mlv::color::skyblue3" ),
		color_pair(mlv::color::skyblue4, "mlv::color::skyblue4" ),
		color_pair(mlv::color::lightskyblue1, "mlv::color::lightskyblue1" ),
		color_pair(mlv::color::lightskyblue2, "mlv::color::lightskyblue2" ),
		color_pair(mlv::color::lightskyblue3, "mlv::color::lightskyblue3" ),
		color_pair(mlv::color::lightskyblue4, "mlv::color::lightskyblue4" ),
		color_pair(mlv::color::slategray1, "mlv::color::slategray1" ),
		color_pair(mlv::color::slategray2, "mlv::color::slategray2" ),
		color_pair(mlv::color::slategray3, "mlv::color::slategray3" ),
		color_pair(mlv::color::slategray4, "mlv::color::slategray4" ),
		color_pair(mlv::color::lightsteelblue1, "mlv::color::lightsteelblue1" ),
		color_pair(mlv::color::lightsteelblue2, "mlv::color::lightsteelblue2" ),
		color_pair(mlv::color::lightsteelblue3, "mlv::color::lightsteelblue3" ),
		color_pair(mlv::color::lightsteelblue4, "mlv::color::lightsteelblue4" ),
		color_pair(mlv::color::lightblue1, "mlv::color::lightblue1" ),
		color_pair(mlv::color::lightblue2, "mlv::color::lightblue2" ),
		color_pair(mlv::color::lightblue3, "mlv::color::lightblue3" ),
		color_pair(mlv::color::lightblue4, "mlv::color::lightblue4" ),
		color_pair(mlv::color::lightcyan1, "mlv::color::lightcyan1" ),
		color_pair(mlv::color::lightcyan2, "mlv::color::lightcyan2" ),
		color_pair(mlv::color::lightcyan3, "mlv::color::lightcyan3" ),
		color_pair(mlv::color::lightcyan4, "mlv::color::lightcyan4" ),
		color_pair(mlv::color::paleturquoise1, "mlv::color::paleturquoise1" ),
		color_pair(mlv::color::paleturquoise2, "mlv::color::paleturquoise2" ),
		color_pair(mlv::color::paleturquoise3, "mlv::color::paleturquoise3" ),
		color_pair(mlv::color::paleturquoise4, "mlv::color::paleturquoise4" ),
		color_pair(mlv::color::cadetblue1, "mlv::color::cadetblue1" ),
		color_pair(mlv::color::cadetblue2, "mlv::color::cadetblue2" ),
		color_pair(mlv::color::cadetblue3, "mlv::color::cadetblue3" ),
		color_pair(mlv::color::cadetblue4, "mlv::color::cadetblue4" ),
		color_pair(mlv::color::turquoise1, "mlv::color::turquoise1" ),
		color_pair(mlv::color::turquoise2, "mlv::color::turquoise2" ),
		color_pair(mlv::color::turquoise3, "mlv::color::turquoise3" ),
		color_pair(mlv::color::turquoise4, "mlv::color::turquoise4" ),
		color_pair(mlv::color::cyan1, "mlv::color::cyan1" ),
		color_pair(mlv::color::cyan2, "mlv::color::cyan2" ),
		color_pair(mlv::color::cyan3, "mlv::color::cyan3" ),
		color_pair(mlv::color::cyan4, "mlv::color::cyan4" ),
		color_pair(mlv::color::darkslategray1, "mlv::color::darkslategray1" ),
		color_pair(mlv::color::darkslategray2, "mlv::color::darkslategray2" ),
		color_pair(mlv::color::darkslategray3, "mlv::color::darkslategray3" ),
		color_pair(mlv::color::darkslategray4, "mlv::color::darkslategray4" ),
		color_pair(mlv::color::aquamarine1, "mlv::color::aquamarine1" ),
		color_pair(mlv::color::aquamarine2, "mlv::color::aquamarine2" ),
		color_pair(mlv::color::aquamarine3, "mlv::color::aquamarine3" ),
		color_pair(mlv::color::aquamarine4, "mlv::color::aquamarine4" ),
		color_pair(mlv::color::darkseagreen1, "mlv::color::darkseagreen1" ),
		color_pair(mlv::color::darkseagreen2, "mlv::color::darkseagreen2" ),
		color_pair(mlv::color::darkseagreen3, "mlv::color::darkseagreen3" ),
		color_pair(mlv::color::darkseagreen4, "mlv::color::darkseagreen4" ),
		color_pair(mlv::color::seagreen1, "mlv::color::seagreen1" ),
		color_pair(mlv::color::seagreen2, "mlv::color::seagreen2" ),
		color_pair(mlv::color::seagreen3, "mlv::color::seagreen3" ),
		color_pair(mlv::color::seagreen4, "mlv::color::seagreen4" ),
		color_pair(mlv::color::palegreen1, "mlv::color::palegreen1" ),
		color_pair(mlv::color::palegreen2, "mlv::color::palegreen2" ),
		color_pair(mlv::color::palegreen3, "mlv::color::palegreen3" ),
		color_pair(mlv::color::palegreen4, "mlv::color::palegreen4" ),
		color_pair(mlv::color::springgreen1, "mlv::color::springgreen1" ),
		color_pair(mlv::color::springgreen2, "mlv::color::springgreen2" ),
		color_pair(mlv::color::springgreen3, "mlv::color::springgreen3" ),
		color_pair(mlv::color::springgreen4, "mlv::color::springgreen4" ),
		color_pair(mlv::color::green1, "mlv::color::green1" ),
		color_pair(mlv::color::green2, "mlv::color::green2" ),
		color_pair(mlv::color::green3, "mlv::color::green3" ),
		color_pair(mlv::color::green4, "mlv::color::green4" ),
		color_pair(mlv::color::chartreuse1, "mlv::color::chartreuse1" ),
		color_pair(mlv::color::chartreuse2, "mlv::color::chartreuse2" ),
		color_pair(mlv::color::chartreuse3, "mlv::color::chartreuse3" ),
		color_pair(mlv::color::chartreuse4, "mlv::color::chartreuse4" ),
		color_pair(mlv::color::olivedrab1, "mlv::color::olivedrab1" ),
		color_pair(mlv::color::olivedrab2, "mlv::color::olivedrab2" ),
		color_pair(mlv::color::olivedrab3, "mlv::color::olivedrab3" ),
		color_pair(mlv::color::olivedrab4, "mlv::color::olivedrab4" ),
		color_pair(mlv::color::darkolivegreen1, "mlv::color::darkolivegreen1" ),
		color_pair(mlv::color::darkolivegreen2, "mlv::color::darkolivegreen2" ),
		color_pair(mlv::color::darkolivegreen3, "mlv::color::darkolivegreen3" ),
		color_pair(mlv::color::darkolivegreen4, "mlv::color::darkolivegreen4" ),
		color_pair(mlv::color::khaki1, "mlv::color::khaki1" ),
		color_pair(mlv::color::khaki2, "mlv::color::khaki2" ),
		color_pair(mlv::color::khaki3, "mlv::color::khaki3" ),
		color_pair(mlv::color::khaki4, "mlv::color::khaki4" ),
		color_pair(mlv::color::lightgoldenrod1, "mlv::color::lightgoldenrod1" ),
		color_pair(mlv::color::lightgoldenrod2, "mlv::color::lightgoldenrod2" ),
		color_pair(mlv::color::lightgoldenrod3, "mlv::color::lightgoldenrod3" ),
		color_pair(mlv::color::lightgoldenrod4, "mlv::color::lightgoldenrod4" ),
		color_pair(mlv::color::lightyellow1, "mlv::color::lightyellow1" ),
		color_pair(mlv::color::lightyellow2, "mlv::color::lightyellow2" ),
		color_pair(mlv::color::lightyellow3, "mlv::color::lightyellow3" ),
		color_pair(mlv::color::lightyellow4, "mlv::color::lightyellow4" ),
		color_pair(mlv::color::yellow1, "mlv::color::yellow1" ),
		color_pair(mlv::color::yellow2, "mlv::color::yellow2" ),
		color_pair(mlv::color::yellow3, "mlv::color::yellow3" ),
		color_pair(mlv::color::yellow4, "mlv::color::yellow4" ),
		color_pair(mlv::color::gold1, "mlv::color::gold1" ),
		color_pair(mlv::color::gold2, "mlv::color::gold2" ),
		color_pair(mlv::color::gold3, "mlv::color::gold3" ),
		color_pair(mlv::color::gold4, "mlv::color::gold4" ),
		color_pair(mlv::color::goldenrod1, "mlv::color::goldenrod1" ),
		color_pair(mlv::color::goldenrod2, "mlv::color::goldenrod2" ),
		color_pair(mlv::color::goldenrod3, "mlv::color::goldenrod3" ),
		color_pair(mlv::color::goldenrod4, "mlv::color::goldenrod4" ),
		color_pair(mlv::color::darkgoldenrod1, "mlv::color::darkgoldenrod1" ),
		color_pair(mlv::color::darkgoldenrod2, "mlv::color::darkgoldenrod2" ),
		color_pair(mlv::color::darkgoldenrod3, "mlv::color::darkgoldenrod3" ),
		color_pair(mlv::color::darkgoldenrod4, "mlv::color::darkgoldenrod4" ),
		color_pair(mlv::color::rosybrown1, "mlv::color::rosybrown1" ),
		color_pair(mlv::color::rosybrown2, "mlv::color::rosybrown2" ),
		color_pair(mlv::color::rosybrown3, "mlv::color::rosybrown3" ),
		color_pair(mlv::color::rosybrown4, "mlv::color::rosybrown4" ),
		color_pair(mlv::color::indianred1, "mlv::color::indianred1" ),
		color_pair(mlv::color::indianred2, "mlv::color::indianred2" ),
		color_pair(mlv::color::indianred3, "mlv::color::indianred3" ),
		color_pair(mlv::color::indianred4, "mlv::color::indianred4" ),
		color_pair(mlv::color::sienna1, "mlv::color::sienna1" ),
		color_pair(mlv::color::sienna2, "mlv::color::sienna2" ),
		color_pair(mlv::color::sienna3, "mlv::color::sienna3" ),
		color_pair(mlv::color::sienna4, "mlv::color::sienna4" ),
		color_pair(mlv::color::burlywood1, "mlv::color::burlywood1" ),
		color_pair(mlv::color::burlywood2, "mlv::color::burlywood2" ),
		color_pair(mlv::color::burlywood3, "mlv::color::burlywood3" ),
		color_pair(mlv::color::burlywood4, "mlv::color::burlywood4" ),
		color_pair(mlv::color::wheat1, "mlv::color::wheat1" ),
		color_pair(mlv::color::wheat2, "mlv::color::wheat2" ),
		color_pair(mlv::color::wheat3, "mlv::color::wheat3" ),
		color_pair(mlv::color::wheat4, "mlv::color::wheat4" ),
		color_pair(mlv::color::tan1, "mlv::color::tan1" ),
		color_pair(mlv::color::tan2, "mlv::color::tan2" ),
		color_pair(mlv::color::tan3, "mlv::color::tan3" ),
		color_pair(mlv::color::tan4, "mlv::color::tan4" ),
		color_pair(mlv::color::chocolate1, "mlv::color::chocolate1" ),
		color_pair(mlv::color::chocolate2, "mlv::color::chocolate2" ),
		color_pair(mlv::color::chocolate3, "mlv::color::chocolate3" ),
		color_pair(mlv::color::chocolate4, "mlv::color::chocolate4" ),
		color_pair(mlv::color::firebrick1, "mlv::color::firebrick1" ),
		color_pair(mlv::color::firebrick2, "mlv::color::firebrick2" ),
		color_pair(mlv::color::firebrick3, "mlv::color::firebrick3" ),
		color_pair(mlv::color::firebrick4, "mlv::color::firebrick4" ),
		color_pair(mlv::color::brown1, "mlv::color::brown1" ),
		color_pair(mlv::color::brown2, "mlv::color::brown2" ),
		color_pair(mlv::color::brown3, "mlv::color::brown3" ),
		color_pair(mlv::color::brown4, "mlv::color::brown4" ),
		color_pair(mlv::color::salmon1, "mlv::color::salmon1" ),
		color_pair(mlv::color::salmon2, "mlv::color::salmon2" ),
		color_pair(mlv::color::salmon3, "mlv::color::salmon3" ),
		color_pair(mlv::color::salmon4, "mlv::color::salmon4" ),
		color_pair(mlv::color::lightsalmon1, "mlv::color::lightsalmon1" ),
		color_pair(mlv::color::lightsalmon2, "mlv::color::lightsalmon2" ),
		color_pair(mlv::color::lightsalmon3, "mlv::color::lightsalmon3" ),
		color_pair(mlv::color::lightsalmon4, "mlv::color::lightsalmon4" ),
		color_pair(mlv::color::orange1, "mlv::color::orange1" ),
		color_pair(mlv::color::orange2, "mlv::color::orange2" ),
		color_pair(mlv::color::orange3, "mlv::color::orange3" ),
		color_pair(mlv::color::orange4, "mlv::color::orange4" ),
		color_pair(mlv::color::darkorange1, "mlv::color::darkorange1" ),
		color_pair(mlv::color::darkorange2, "mlv::color::darkorange2" ),
		color_pair(mlv::color::darkorange3, "mlv::color::darkorange3" ),
		color_pair(mlv::color::darkorange4, "mlv::color::darkorange4" ),
		color_pair(mlv::color::coral1, "mlv::color::coral1" ),
		color_pair(mlv::color::coral2, "mlv::color::coral2" ),
		color_pair(mlv::color::coral3, "mlv::color::coral3" ),
		color_pair(mlv::color::coral4, "mlv::color::coral4" ),
		color_pair(mlv::color::tomato1, "mlv::color::tomato1" ),
		color_pair(mlv::color::tomato2, "mlv::color::tomato2" ),
		color_pair(mlv::color::tomato3, "mlv::color::tomato3" ),
		color_pair(mlv::color::tomato4, "mlv::color::tomato4" ),
		color_pair(mlv::color::orangered1, "mlv::color::orangered1" ),
		color_pair(mlv::color::orangered2, "mlv::color::orangered2" ),
		color_pair(mlv::color::orangered3, "mlv::color::orangered3" ),
		color_pair(mlv::color::orangered4, "mlv::color::orangered4" ),
		color_pair(mlv::color::red1, "mlv::color::red1" ),
		color_pair(mlv::color::red2, "mlv::color::red2" ),
		color_pair(mlv::color::red3, "mlv::color::red3" ),
		color_pair(mlv::color::red4, "mlv::color::red4" ),
		color_pair(mlv::color::deeppink1, "mlv::color::deeppink1" ),
		color_pair(mlv::color::deeppink2, "mlv::color::deeppink2" ),
		color_pair(mlv::color::deeppink3, "mlv::color::deeppink3" ),
		color_pair(mlv::color::deeppink4, "mlv::color::deeppink4" ),
		color_pair(mlv::color::hotpink1, "mlv::color::hotpink1" ),
		color_pair(mlv::color::hotpink2, "mlv::color::hotpink2" ),
		color_pair(mlv::color::hotpink3, "mlv::color::hotpink3" ),
		color_pair(mlv::color::hotpink4, "mlv::color::hotpink4" ),
		color_pair(mlv::color::pink1, "mlv::color::pink1" ),
		color_pair(mlv::color::pink2, "mlv::color::pink2" ),
		color_pair(mlv::color::pink3, "mlv::color::pink3" ),
		color_pair(mlv::color::pink4, "mlv::color::pink4" ),
		color_pair(mlv::color::lightpink1, "mlv::color::lightpink1" ),
		color_pair(mlv::color::lightpink2, "mlv::color::lightpink2" ),
		color_pair(mlv::color::lightpink3, "mlv::color::lightpink3" ),
		color_pair(mlv::color::lightpink4, "mlv::color::lightpink4" ),
		color_pair(mlv::color::palevioletred1, "mlv::color::palevioletred1" ),
		color_pair(mlv::color::palevioletred2, "mlv::color::palevioletred2" ),
		color_pair(mlv::color::palevioletred3, "mlv::color::palevioletred3" ),
		color_pair(mlv::color::palevioletred4, "mlv::color::palevioletred4" ),
		color_pair(mlv::color::maroon1, "mlv::color::maroon1" ),
		color_pair(mlv::color::maroon2, "mlv::color::maroon2" ),
		color_pair(mlv::color::maroon3, "mlv::color::maroon3" ),
		color_pair(mlv::color::maroon4, "mlv::color::maroon4" ),
		color_pair(mlv::color::violetred1, "mlv::color::violetred1" ),
		color_pair(mlv::color::violetred2, "mlv::color::violetred2" ),
		color_pair(mlv::color::violetred3, "mlv::color::violetred3" ),
		color_pair(mlv::color::violetred4, "mlv::color::violetred4" ),
		color_pair(mlv::color::magenta1, "mlv::color::magenta1" ),
		color_pair(mlv::color::magenta2, "mlv::color::magenta2" ),
		color_pair(mlv::color::magenta3, "mlv::color::magenta3" ),
		color_pair(mlv::color::magenta4, "mlv::color::magenta4" ),
		color_pair(mlv::color::orchid1, "mlv::color::orchid1" ),
		color_pair(mlv::color::orchid2, "mlv::color::orchid2" ),
		color_pair(mlv::color::orchid3, "mlv::color::orchid3" ),
		color_pair(mlv::color::orchid4, "mlv::color::orchid4" ),
		color_pair(mlv::color::plum1, "mlv::color::plum1" ),
		color_pair(mlv::color::plum2, "mlv::color::plum2" ),
		color_pair(mlv::color::plum3, "mlv::color::plum3" ),
		color_pair(mlv::color::plum4, "mlv::color::plum4" ),
		color_pair(mlv::color::mediumorchid1, "mlv::color::mediumorchid1" ),
		color_pair(mlv::color::mediumorchid2, "mlv::color::mediumorchid2" ),
		color_pair(mlv::color::mediumorchid3, "mlv::color::mediumorchid3" ),
		color_pair(mlv::color::mediumorchid4, "mlv::color::mediumorchid4" ),
		color_pair(mlv::color::darkorchid1, "mlv::color::darkorchid1" ),
		color_pair(mlv::color::darkorchid2, "mlv::color::darkorchid2" ),
		color_pair(mlv::color::darkorchid3, "mlv::color::darkorchid3" ),
		color_pair(mlv::color::darkorchid4, "mlv::color::darkorchid4" ),
		color_pair(mlv::color::purple1, "mlv::color::purple1" ),
		color_pair(mlv::color::purple2, "mlv::color::purple2" ),
		color_pair(mlv::color::purple3, "mlv::color::purple3" ),
		color_pair(mlv::color::purple4, "mlv::color::purple4" ),
		color_pair(mlv::color::mediumpurple1, "mlv::color::mediumpurple1" ),
		color_pair(mlv::color::mediumpurple2, "mlv::color::mediumpurple2" ),
		color_pair(mlv::color::mediumpurple3, "mlv::color::mediumpurple3" ),
		color_pair(mlv::color::mediumpurple4, "mlv::color::mediumpurple4" ),
		color_pair(mlv::color::thistle1, "mlv::color::thistle1" ),
		color_pair(mlv::color::thistle2, "mlv::color::thistle2" ),
		color_pair(mlv::color::thistle3, "mlv::color::thistle3" ),
		color_pair(mlv::color::thistle4, "mlv::color::thistle4" ),
		color_pair(mlv::color::gray0, "mlv::color::gray0" ),
		color_pair(mlv::color::grey0, "mlv::color::grey0" ),
		color_pair(mlv::color::gray1, "mlv::color::gray1" ),
		color_pair(mlv::color::grey1, "mlv::color::grey1" ),
		color_pair(mlv::color::gray2, "mlv::color::gray2" ),
		color_pair(mlv::color::grey2, "mlv::color::grey2" ),
		color_pair(mlv::color::gray3, "mlv::color::gray3" ),
		color_pair(mlv::color::grey3, "mlv::color::grey3" ),
		color_pair(mlv::color::gray4, "mlv::color::gray4" ),
		color_pair(mlv::color::grey4, "mlv::color::grey4" ),
		color_pair(mlv::color::gray5, "mlv::color::gray5" ),
		color_pair(mlv::color::grey5, "mlv::color::grey5" ),
		color_pair(mlv::color::gray6, "mlv::color::gray6" ),
		color_pair(mlv::color::grey6, "mlv::color::grey6" ),
		color_pair(mlv::color::gray7, "mlv::color::gray7" ),
		color_pair(mlv::color::grey7, "mlv::color::grey7" ),
		color_pair(mlv::color::gray8, "mlv::color::gray8" ),
		color_pair(mlv::color::grey8, "mlv::color::grey8" ),
		color_pair(mlv::color::gray9, "mlv::color::gray9" ),
		color_pair(mlv::color::grey9, "mlv::color::grey9" ),
		color_pair(mlv::color::gray10, "mlv::color::gray10" ),
		color_pair(mlv::color::grey10, "mlv::color::grey10" ),
		color_pair(mlv::color::gray11, "mlv::color::gray11" ),
		color_pair(mlv::color::grey11, "mlv::color::grey11" ),
		color_pair(mlv::color::gray12, "mlv::color::gray12" ),
		color_pair(mlv::color::grey12, "mlv::color::grey12" ),
		color_pair(mlv::color::gray13, "mlv::color::gray13" ),
		color_pair(mlv::color::grey13, "mlv::color::grey13" ),
		color_pair(mlv::color::gray14, "mlv::color::gray14" ),
		color_pair(mlv::color::grey14, "mlv::color::grey14" ),
		color_pair(mlv::color::gray15, "mlv::color::gray15" ),
		color_pair(mlv::color::grey15, "mlv::color::grey15" ),
		color_pair(mlv::color::gray16, "mlv::color::gray16" ),
		color_pair(mlv::color::grey16, "mlv::color::grey16" ),
		color_pair(mlv::color::gray17, "mlv::color::gray17" ),
		color_pair(mlv::color::grey17, "mlv::color::grey17" ),
		color_pair(mlv::color::gray18, "mlv::color::gray18" ),
		color_pair(mlv::color::grey18, "mlv::color::grey18" ),
		color_pair(mlv::color::gray19, "mlv::color::gray19" ),
		color_pair(mlv::color::grey19, "mlv::color::grey19" ),
		color_pair(mlv::color::gray20, "mlv::color::gray20" ),
		color_pair(mlv::color::grey20, "mlv::color::grey20" ),
		color_pair(mlv::color::gray21, "mlv::color::gray21" ),
		color_pair(mlv::color::grey21, "mlv::color::grey21" ),
		color_pair(mlv::color::gray22, "mlv::color::gray22" ),
		color_pair(mlv::color::grey22, "mlv::color::grey22" ),
		color_pair(mlv::color::gray23, "mlv::color::gray23" ),
		color_pair(mlv::color::grey23, "mlv::color::grey23" ),
		color_pair(mlv::color::gray24, "mlv::color::gray24" ),
		color_pair(mlv::color::grey24, "mlv::color::grey24" ),
		color_pair(mlv::color::gray25, "mlv::color::gray25" ),
		color_pair(mlv::color::grey25, "mlv::color::grey25" ),
		color_pair(mlv::color::gray26, "mlv::color::gray26" ),
		color_pair(mlv::color::grey26, "mlv::color::grey26" ),
		color_pair(mlv::color::gray27, "mlv::color::gray27" ),
		color_pair(mlv::color::grey27, "mlv::color::grey27" ),
		color_pair(mlv::color::gray28, "mlv::color::gray28" ),
		color_pair(mlv::color::grey28, "mlv::color::grey28" ),
		color_pair(mlv::color::gray29, "mlv::color::gray29" ),
		color_pair(mlv::color::grey29, "mlv::color::grey29" ),
		color_pair(mlv::color::gray30, "mlv::color::gray30" ),
		color_pair(mlv::color::grey30, "mlv::color::grey30" ),
		color_pair(mlv::color::gray31, "mlv::color::gray31" ),
		color_pair(mlv::color::grey31, "mlv::color::grey31" ),
		color_pair(mlv::color::gray32, "mlv::color::gray32" ),
		color_pair(mlv::color::grey32, "mlv::color::grey32" ),
		color_pair(mlv::color::gray33, "mlv::color::gray33" ),
		color_pair(mlv::color::grey33, "mlv::color::grey33" ),
		color_pair(mlv::color::gray34, "mlv::color::gray34" ),
		color_pair(mlv::color::grey34, "mlv::color::grey34" ),
		color_pair(mlv::color::gray35, "mlv::color::gray35" ),
		color_pair(mlv::color::grey35, "mlv::color::grey35" ),
		color_pair(mlv::color::gray36, "mlv::color::gray36" ),
		color_pair(mlv::color::grey36, "mlv::color::grey36" ),
		color_pair(mlv::color::gray37, "mlv::color::gray37" ),
		color_pair(mlv::color::grey37, "mlv::color::grey37" ),
		color_pair(mlv::color::gray38, "mlv::color::gray38" ),
		color_pair(mlv::color::grey38, "mlv::color::grey38" ),
		color_pair(mlv::color::gray39, "mlv::color::gray39" ),
		color_pair(mlv::color::grey39, "mlv::color::grey39" ),
		color_pair(mlv::color::gray40, "mlv::color::gray40" ),
		color_pair(mlv::color::grey40, "mlv::color::grey40" ),
		color_pair(mlv::color::gray41, "mlv::color::gray41" ),
		color_pair(mlv::color::grey41, "mlv::color::grey41" ),
		color_pair(mlv::color::gray42, "mlv::color::gray42" ),
		color_pair(mlv::color::grey42, "mlv::color::grey42" ),
		color_pair(mlv::color::gray43, "mlv::color::gray43" ),
		color_pair(mlv::color::grey43, "mlv::color::grey43" ),
		color_pair(mlv::color::gray44, "mlv::color::gray44" ),
		color_pair(mlv::color::grey44, "mlv::color::grey44" ),
		color_pair(mlv::color::gray45, "mlv::color::gray45" ),
		color_pair(mlv::color::grey45, "mlv::color::grey45" ),
		color_pair(mlv::color::gray46, "mlv::color::gray46" ),
		color_pair(mlv::color::grey46, "mlv::color::grey46" ),
		color_pair(mlv::color::gray47, "mlv::color::gray47" ),
		color_pair(mlv::color::grey47, "mlv::color::grey47" ),
		color_pair(mlv::color::gray48, "mlv::color::gray48" ),
		color_pair(mlv::color::grey48, "mlv::color::grey48" ),
		color_pair(mlv::color::gray49, "mlv::color::gray49" ),
		color_pair(mlv::color::grey49, "mlv::color::grey49" ),
		color_pair(mlv::color::gray50, "mlv::color::gray50" ),
		color_pair(mlv::color::grey50, "mlv::color::grey50" ),
		color_pair(mlv::color::gray51, "mlv::color::gray51" ),
		color_pair(mlv::color::grey51, "mlv::color::grey51" ),
		color_pair(mlv::color::gray52, "mlv::color::gray52" ),
		color_pair(mlv::color::grey52, "mlv::color::grey52" ),
		color_pair(mlv::color::gray53, "mlv::color::gray53" ),
		color_pair(mlv::color::grey53, "mlv::color::grey53" ),
		color_pair(mlv::color::gray54, "mlv::color::gray54" ),
		color_pair(mlv::color::grey54, "mlv::color::grey54" ),
		color_pair(mlv::color::gray55, "mlv::color::gray55" ),
		color_pair(mlv::color::grey55, "mlv::color::grey55" ),
		color_pair(mlv::color::gray56, "mlv::color::gray56" ),
		color_pair(mlv::color::grey56, "mlv::color::grey56" ),
		color_pair(mlv::color::gray57, "mlv::color::gray57" ),
		color_pair(mlv::color::grey57, "mlv::color::grey57" ),
		color_pair(mlv::color::gray58, "mlv::color::gray58" ),
		color_pair(mlv::color::grey58, "mlv::color::grey58" ),
		color_pair(mlv::color::gray59, "mlv::color::gray59" ),
		color_pair(mlv::color::grey59, "mlv::color::grey59" ),
		color_pair(mlv::color::gray60, "mlv::color::gray60" ),
		color_pair(mlv::color::grey60, "mlv::color::grey60" ),
		color_pair(mlv::color::gray61, "mlv::color::gray61" ),
		color_pair(mlv::color::grey61, "mlv::color::grey61" ),
		color_pair(mlv::color::gray62, "mlv::color::gray62" ),
		color_pair(mlv::color::grey62, "mlv::color::grey62" ),
		color_pair(mlv::color::gray63, "mlv::color::gray63" ),
		color_pair(mlv::color::grey63, "mlv::color::grey63" ),
		color_pair(mlv::color::gray64, "mlv::color::gray64" ),
		color_pair(mlv::color::grey64, "mlv::color::grey64" ),
		color_pair(mlv::color::gray65, "mlv::color::gray65" ),
		color_pair(mlv::color::grey65, "mlv::color::grey65" ),
		color_pair(mlv::color::gray66, "mlv::color::gray66" ),
		color_pair(mlv::color::grey66, "mlv::color::grey66" ),
		color_pair(mlv::color::gray67, "mlv::color::gray67" ),
		color_pair(mlv::color::grey67, "mlv::color::grey67" ),
		color_pair(mlv::color::gray68, "mlv::color::gray68" ),
		color_pair(mlv::color::grey68, "mlv::color::grey68" ),
		color_pair(mlv::color::gray69, "mlv::color::gray69" ),
		color_pair(mlv::color::grey69, "mlv::color::grey69" ),
		color_pair(mlv::color::gray70, "mlv::color::gray70" ),
		color_pair(mlv::color::grey70, "mlv::color::grey70" ),
		color_pair(mlv::color::gray71, "mlv::color::gray71" ),
		color_pair(mlv::color::grey71, "mlv::color::grey71" ),
		color_pair(mlv::color::gray72, "mlv::color::gray72" ),
		color_pair(mlv::color::grey72, "mlv::color::grey72" ),
		color_pair(mlv::color::gray73, "mlv::color::gray73" ),
		color_pair(mlv::color::grey73, "mlv::color::grey73" ),
		color_pair(mlv::color::gray74, "mlv::color::gray74" ),
		color_pair(mlv::color::grey74, "mlv::color::grey74" ),
		color_pair(mlv::color::gray75, "mlv::color::gray75" ),
		color_pair(mlv::color::grey75, "mlv::color::grey75" ),
		color_pair(mlv::color::gray76, "mlv::color::gray76" ),
		color_pair(mlv::color::grey76, "mlv::color::grey76" ),
		color_pair(mlv::color::gray77, "mlv::color::gray77" ),
		color_pair(mlv::color::grey77, "mlv::color::grey77" ),
		color_pair(mlv::color::gray78, "mlv::color::gray78" ),
		color_pair(mlv::color::grey78, "mlv::color::grey78" ),
		color_pair(mlv::color::gray79, "mlv::color::gray79" ),
		color_pair(mlv::color::grey79, "mlv::color::grey79" ),
		color_pair(mlv::color::gray80, "mlv::color::gray80" ),
		color_pair(mlv::color::grey80, "mlv::color::grey80" ),
		color_pair(mlv::color::gray81, "mlv::color::gray81" ),
		color_pair(mlv::color::grey81, "mlv::color::grey81" ),
		color_pair(mlv::color::gray82, "mlv::color::gray82" ),
		color_pair(mlv::color::grey82, "mlv::color::grey82" ),
		color_pair(mlv::color::gray83, "mlv::color::gray83" ),
		color_pair(mlv::color::grey83, "mlv::color::grey83" ),
		color_pair(mlv::color::gray84, "mlv::color::gray84" ),
		color_pair(mlv::color::grey84, "mlv::color::grey84" ),
		color_pair(mlv::color::gray85, "mlv::color::gray85" ),
		color_pair(mlv::color::grey85, "mlv::color::grey85" ),
		color_pair(mlv::color::gray86, "mlv::color::gray86" ),
		color_pair(mlv::color::grey86, "mlv::color::grey86" ),
		color_pair(mlv::color::gray87, "mlv::color::gray87" ),
		color_pair(mlv::color::grey87, "mlv::color::grey87" ),
		color_pair(mlv::color::gray88, "mlv::color::gray88" ),
		color_pair(mlv::color::grey88, "mlv::color::grey88" ),
		color_pair(mlv::color::gray89, "mlv::color::gray89" ),
		color_pair(mlv::color::grey89, "mlv::color::grey89" ),
		color_pair(mlv::color::gray90, "mlv::color::gray90" ),
		color_pair(mlv::color::grey90, "mlv::color::grey90" ),
		color_pair(mlv::color::gray91, "mlv::color::gray91" ),
		color_pair(mlv::color::grey91, "mlv::color::grey91" ),
		color_pair(mlv::color::gray92, "mlv::color::gray92" ),
		color_pair(mlv::color::grey92, "mlv::color::grey92" ),
		color_pair(mlv::color::gray93, "mlv::color::gray93" ),
		color_pair(mlv::color::grey93, "mlv::color::grey93" ),
		color_pair(mlv::color::gray94, "mlv::color::gray94" ),
		color_pair(mlv::color::grey94, "mlv::color::grey94" ),
		color_pair(mlv::color::gray95, "mlv::color::gray95" ),
		color_pair(mlv::color::grey95, "mlv::color::grey95" ),
		color_pair(mlv::color::gray96, "mlv::color::gray96" ),
		color_pair(mlv::color::grey96, "mlv::color::grey96" ),
		color_pair(mlv::color::gray97, "mlv::color::gray97" ),
		color_pair(mlv::color::grey97, "mlv::color::grey97" ),
		color_pair(mlv::color::gray98, "mlv::color::gray98" ),
		color_pair(mlv::color::grey98, "mlv::color::grey98" ),
		color_pair(mlv::color::gray99, "mlv::color::gray99" ),
		color_pair(mlv::color::grey99, "mlv::color::grey99" ),
		color_pair(mlv::color::gray100, "mlv::color::gray100" ),
		color_pair(mlv::color::grey100, "mlv::color::grey100" ),
		color_pair(mlv::color::dark_grey, "mlv::color::dark_grey" ),
		color_pair(mlv::color::darkgrey, "mlv::color::darkgrey" ),
		color_pair(mlv::color::dark_gray, "mlv::color::dark_gray" ),
		color_pair(mlv::color::darkgray, "mlv::color::darkgray" ),
		color_pair(mlv::color::dark_blue, "mlv::color::dark_blue" ),
		color_pair(mlv::color::darkblue, "mlv::color::darkblue" ),
		color_pair(mlv::color::dark_cyan, "mlv::color::dark_cyan" ),
		color_pair(mlv::color::darkcyan, "mlv::color::darkcyan" ),
		color_pair(mlv::color::dark_magenta, "mlv::color::dark_magenta" ),
		color_pair(mlv::color::darkmagenta, "mlv::color::darkmagenta" ),
		color_pair(mlv::color::dark_red, "mlv::color::dark_red" ),
		color_pair(mlv::color::darkred, "mlv::color::darkred" ),
		color_pair(mlv::color::light_green, "mlv::color::light_green" ),
		color_pair(mlv::color::lightgreen, "mlv::color::lightgreen" )
	};

	int largeur = 640;
	int hauteur = 480;
	int nb_case_largeur = std::sqrt(NB_COULEUR);
	int largeur_case = largeur/nb_case_largeur;
	int hauteur_case = hauteur/nb_case_largeur;
	int integerX, integerY, couleur_obtenu, posX, posY;

	mlv::point_t mouse_position;

	//
	// Créé et affiche la fenêtre
	//
	mlv::window_t window( "beginner - 9 - colors", "colors", 640, 480 );

	while( 1 ){
		int i;
		//
		// Nettoie l'écran pour un nouvel affichage
		//
		window.clear( mlv::color::black );

		//
		// Affiche le rectangle de ième couleur
		//
		for( i=0; i<NB_COULEUR; i++){
			posX = i%nb_case_largeur;
			posY = i/nb_case_largeur;
			window.draw_filled_rectangle(
				mlv::point_t( posX*largeur_case, posY*hauteur_case ),
				largeur_case, hauteur_case,
				couleurs[i].first
			);
		}
		//
		// Met a jour l'affichage.
		//
		window.update();

		//
		// Attends que l'utilisateur clique sur le bouton gauche de la souris
		//
		mouse_position = window.wait_mouse();

		integerX = mouse_position.x/( largeur_case);
		integerY = mouse_position.y/( hauteur_case);
		couleur_obtenu= integerX+integerY*nb_case_largeur;

		if( couleur_obtenu<NB_COULEUR ){
			std::cout << "Couleur : " << couleurs[couleur_obtenu].second 
				<< std::endl;
			window.draw_text_box(
				mlv::box::text_t(
					mlv::point_t(0, 0), 
					couleurs[ couleur_obtenu ].second,
					9,
					mlv::color::red, mlv::color::green, mlv::color::black,
					mlv::text::center
				)
			);
		}
		
		//
		// Met à jour l'affichage.
		//
		window.update();

		window.wait_mouse(mouse_position);
	}

	//
	// Ferme la fenêtre
	//
	MLV_free_window();

	return 0;
}

/*
 *   This file is part of the MLV Library.
 *
 *   Copyright (C) 2016 Adrien Boussicault
 *
 *
 *    This Library is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This Library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this Library.  If not, see <http://www.gnu.org/licenses/>.
 */
